const quotes = [
    { text: "Courage is not the absence of fear, but the ability to act despite it.", author: "Anonymous" },
    { text: "Kindness is a language the deaf can hear and the blind can see.", author: "Mark Twain" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Every great achievement was once considered impossible.", author: "Anonymous" },
    { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The strongest people make time to help others, no matter how busy they are.", author: "Anonymous" },
    { text: "Courage doesn't always roar. Sometimes it's the quiet voice at the end of the day saying, 'I'll try again tomorrow.'", author: "Mary Anne Radmacher" },
    { text: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", author: "Patricia Bath" },
    { text: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke" },
    { text: "Happiness is not a destination, it's a way of life.", author: "Anonymous" },
    { text: "The future starts today, not tomorrow.", author: "Pope John Paul II" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "Kindness is a gift everyone can afford to give.", author: "Anonymous" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama XIV" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", author: "Patricia Bath" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },  
    { text: "Happiness is a journey, not a destination.", author: "Buddha" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Motivation comes from working on things we care about.", author: "Sheryl Sandberg" },
    { text: "Invest the first hour of the morning, for it will merit for you the current day.", author: "William Wilberforce" },
    { text: "The heights by great men reached and kept were not attained in sudden flight, but they, while their companions slept, toiled every night.", author: "Henry Wadsworth Longfellow" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "Nothing will work unless you do.", author: "Maya Angelou" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "There are no traffic jams on the extra mile.", author: "Zig Ziglar" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
    { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama XIV" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", author: "Patricia Bath" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { text: "Wisdom is found in the journey, not the destination.", author: "Anonymous" }, 
];
function getRandomQuote() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}

function displayQuote() {
    const quote = getRandomQuote();
    document.getElementById("quoteText").textContent = quote.text;
    document.getElementById("author").textContent = "- " + quote.author;
}

displayQuote();

document.getElementById("quote").addEventListener("click", function() {
    displayQuote();
});


